### ISSUE TITLE
Nomenclature of Program Files

### ISSUE THREAD

**Issue by sanjitschouhan** [rustindia/Rust-for-undergrads#38]
- [x] Rename all program files According to their content
- [ ] Give Numbers to programs based on level of difficulty

**Comment by farseenabdulsalam** [comment]
I am thinking about organizing programs as follows:
Trivial: hello world, sum of numbers, multiplication table, etc. Which is again subdivided into strings, numbers, vector, etc.
Algorithms: subdivided into sorting, searching, coding problems, etc

**Comment by ranjithrajv** [comment]
Sub folders?

**Comment by farseenabdulsalam** [comment]
Yes

**Comment by ranjithrajv** [comment]
Sounds good, please go ahead.

**Comment by farseenabdulsalam** [comment]
- [ ]  Rename all program files According to their content.
I think this is done now.

**Comment by theharshitgarg** [comment]
I would like to take up this if it is open?

**Comment by sanjitschouhan** [comment]
@theharshitgarg all files are already named, and as @thefzsalam arranged them in folders, numbering is not required I guess. I'm clossing this.
