### ISSUE TITLE
Improvement in Language used in Readme

### ISSUE THREAD

**Issue by ishanjain28** [rustindia/Rust-for-undergrads#63]
The Aim for this project as taken from the readme currently states, 

> Encouraging undergrads to re-write C/C++ questions in their academics, job interview and programming practice problems into Rust language.

I believe, The language used in this sentence is slightly unwelcoming and attracts attention of a set of people that might not be the best for the project and rust community.

I suggest, Changing it to something more appropriate like, 

> Enabling undergrads to write projects sets from Academics, Job Interviews and Programming practice problems in Rust Language.

**Comment by lancelafontaine** [comment]
I agree with the above, and would also like to add that the word "evangelize" is very strong, and has been used in the context of holy wars and crusades, which in my opinion does not benefit the Rust community at large. It may be worth considering using a more neutral term like "advocate" or even just "demonstrate".

**Comment by ranjithrajv** [comment]
@lancelafontaine replaced evangelize with advocate
https://github.com/rustindia/Rust-for-undergrads/commit/215cb0c15e2a9846b6ecd1bec5729dd364d89474

Thanks for your suggestion. Keep suggesting/contributing.
